apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: collabora-online
  namespace: collabora
spec:
  interval: 30m
  chart:
    spec:
      chart: collabora-online
      version: "1.1.x"

      sourceRef:
        kind: HelmRepository
        name: collabora-online
        namespace: collabora
      interval: 24h
  values:
    # One replica is enough for my current use case:
    replicaCount: 1
    # According to the documentation, the Horizontal Pod Autoscaling should be disabled for now,
    # since it breaks some other features:
    autoscaling:
      enabled: false
