apiVersion: v1
kind: Secret
metadata:
    name: secret-superuser
data:
    password: ENC[AES256_GCM,data:qRh0r3eS89u7CL/E6U6byEBwo4555Rl6qG+qA+DnfsdK5iLaepzPjOFQhrQYj3pwJ/YbdU8dOEMD41nGiPKFH+ooD2H14JGZ,iv:geyRhL7jQCdowERvi997OETN5tQVQwzgnKIOtgZS6lg=,tag:f7IIeAF6zWayQMeXvFx1mQ==,type:str]
    username: ENC[AES256_GCM,data:8nQlNWKNEgw=,iv:TQL3GYFjil//r67qrII8hsft1dlBZhFhVjYhIXXAZtE=,tag:rv7o/rkPDNoENm9U+cSI3w==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBPa1hlRGlXUUpnZFpidnoz
            WHkyVGZKYkFkZHBGSnRhRE5pNmNOZkwyc0VvClBjRzkxVFl4VHZhKzg3b1hHOVZU
            UHFFdCs3eWUrTXJtcnk3VUN5Y2RtL1EKLS0tIDRuSHg4MnpYbnZSN3JYc2NFUVJz
            K1JkMmZ5bGFFM3FqMlJBN0lUWVE4STQKXgb+bvk0gAysHOI3ljR+kspZ3CxETj1L
            x9HwFRmwgAyLFsTw0Uyaw5gACqy2oTCAH6Unvfy4om/QR62EsqrqmQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-15T01:17:07Z"
    mac: ENC[AES256_GCM,data:Lis1/+LFbEUngfBtVpWVTh+lo4BTcHHM3p3ofOuYlcGuavquhUiW77ksNOnD6woInNlbAbmHN2oCO/HD0Bqfbf6V43Br+OqRaKgFF7GbmUvCpat8JUvHOCm1X0fH40I7rwMz5XGf2ITeVK72VpXu3nFwFrJk77EYue0erUYYCHk=,iv:HA3xRe+WRLRFaHzTWUqs2fm4K9czgb678t397Ja07Uk=,tag:hcTUDbu/CUxC3Zz6S06MsA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
