apiVersion: v1
kind: Secret
metadata:
    name: db-encryption
    namespace: homarr
data:
    db-encryption-key: ENC[AES256_GCM,data:q6aRK/38+eqh7D1GJ+ULOGvHvhj0HZdeUQAnFKSHLVeNljahn6eI1SF+v1eAxCC+nJ2mdbtb2o1V5dU8ZMCBuliW9Wn2MQw5Qkd/8qanJWdCKWLEOSyhqA==,iv:9bxdZ+x62gcIsXtWlYOdDeKNu357fpDBu7LHF8woZD8=,tag:iR/Xvpamu7a0MjvCisYIqQ==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlcFNGdnFvV1g4NkFTVVdk
            TzZOOGRyZ1VnL0k3aFpGNWtwbjlLTzNyVTJjCldsQmYwbE5sMXE0MDRHOThUcHVC
            bWt3SDM4TVc2ekJ5OVpQTGZQNVNXN2cKLS0tIElVZTB6K1RvS3dGbE5qcG5uSkRv
            MEJPUTBYK1VwTVFndktlb1RGb21iRjAKVZrnTIIjklrJy6qpPe9oMN1I59M1coE2
            7mxJRu8UyNhK+9MrLgq6Noz/T4W/Em6qnqTGIIZBzqjuCYTkYrsgqw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-13T15:04:22Z"
    mac: ENC[AES256_GCM,data:dTvVKPUamoT492j3AO0CZ52Bz/9eE4wFdAZ3ZdeqExLk6eTEU3vHmadTJ51ayDp6WuHC3XCSOdpR6P9iUvTkuvx7maetU1oicZO2HseyBpBVjWjRoBR1i/FAS/HlWSbapYggmpKIqN+Sq/EAyAeAXGgK3mcxOiJU+9dUV0xIs9U=,iv:S0MK0CaBFXcbsA/An7B7Qv7Y4SywNNdP40WQCVu2lnw=,tag:C4AI/prHLPQZnqAzncKvxg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
