apiVersion: v1
kind: Secret
metadata:
    name: audiobookshelf-tunnel-credentials
data:
    credentials.json: ENC[AES256_GCM,data:neZS27cAeBmCpfZKX9JZhN/Gika8L5VoMb9+jldq8rDUusKv/VEAtswUe8ggEKQbtw7975fa7x2BXYTVDSKFqXqbOcDZGcyZSYLfjTZfXjg1zhO1OHnq0K4GVxHyIG/hBr09gTRd0jRK/WLBjVknNldLo3ka/0lnBNwwIJ6lPxPXdz4NhRDXgQNEF/sPRGBswPDdTzW63YqKZEWo6B8SaELHKSr25vNSjPxrTo0ZpW88GYnfH6xntMy+Fi/bu34ZwL31sTGzhm/XnD+60Eai2iPSohRQJLJ1XTCPVLGCuUhPqSyLAGY7Wdj2wfs=,iv:1NbQyMRt7SeaFAQTBdkh/tjUa0GFWpdN9looFQjN15I=,tag:/ufgjx/z/HENDzrAbC1YKg==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHQk1MQWNBTUVKbHZoOW12
            cnFEOWpwNE5xV2xSc2Q0WVE1eXJhRktBVnp3Ck5LYW53Ui84VXE4WHdUdGJLTXBw
            Z0Q2eHhIQTAzekJqdUUxZGEralJhKzgKLS0tIFlxOGZjVzdpVzFTbUp1RnNGNmY4
            WjVwTHQ4SEZDVDJNblBFamZPTlZ0ZzgKsqoGX+Bzk55mV9WqOWZ/Q1pbZywmPu7D
            K+0RH4WaX86J/gIQfkJuQLeMGFYW+UgeoyN9WTurSXwWVOweQHclUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-17T16:15:15Z"
    mac: ENC[AES256_GCM,data:SEmzg02/Hgj7B+j4W50HsPVfNUU1GbmN1MkAye8zrP+I4ZEU3r0q+pXXaztVdkfPdzssIaHPrqp5bhGRmZN3XzNu4ZAl0gSRTOPyCXO/6SgK7pFn9kDb9oRyboq4HdepcPI67wby8MWOIWkNHuX3/upB7KIwg+7Hmqrz88LesZY=,iv:g45rAUcZ6C7Y7tVty8gM61g9UQ3MTuLxXAxbnlq8Ky4=,tag:psmw0hhH/wIO1n6+8ptpkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
