apiVersion: v1
kind: Secret
metadata:
    name: tunnel-credentials
    namespace: linkding
data:
    credentials.json: ENC[AES256_GCM,data:j/dBEI22OsemwM/ZLaXqDCXlcLLSk4olPcHYqVJLW+ZojWBNLBEB4pnVxAdaj+9IDOQvp4580UHwLdsEJ/bUXzSYlbiEKBbIapgarenf+tfOdyDgHHWUtyfw9oJwPMQL4sXUxpoc5QrfZ+6Fv9t4yUFeILlFVr4g9JB3lG0sIdgnLdIM8X7LC+9tl3YX/GC5V4YanLAVOKgwxmDYqosOF+vIesnUSpOxIJGCkcAiySkzzQg4kX2IRKS6C5ljVwZMQvlloQQxhgKwCWoiHOsmBumg0GIQuStsXukf0zOythIbREllMG2Iy3C8bBs=,iv:IN6j/O4ilznJ1dCCj8je1hhXABMnhMFWtSxvsWKJ8LA=,tag:D3gtw3eu5cmg8nON+vNsfg==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxaHc3dG93WWpxNE9tSnZE
            WFdTODF3SXhneTg0d0k1WDkvNHROWjRhVEc4Ck5hRnFSNWJ4OWpYbGJuakxZWUNn
            cVRKcXFCRUdXZXQ3b0wra0N4SDNzUUkKLS0tIEdRcWoyOGFyVVdxNHJGbjlCa0FK
            L09VdHJRWlp2WkVzQjkxTkt0QmpkTVUKky9aKcZDL3FiTjZE3KOTfiiRgc96dRbH
            4vRsuJV/0Of2au03kvwqNXZlKsJsAPQGyqVuRw2SRx4yuHNGYmCGSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-04T00:34:35Z"
    mac: ENC[AES256_GCM,data:ONgkqU7mYmZ3udtg6mjzV90y8VXHZXpV1fVneJBHqwh5/Mx9QrpBTRbxrEZRGVPsVGGXrC5OLJ9sEllrzlkhKKqbzLIOko/747HEZAKaA5Uu5DTvwmGbv7pzzeUoe+UOlw+PAeXtRHk+QQ17NyynLnU0BuJ4Ixcjfv33KFCpIZM=,iv:/UvOAYMffk+os7WH0cpa8g0jlgonEwYwy2lQ+qMMZYo=,tag:gVrZ7Bhp7sqJ1KLm2LNgXA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
