apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: linkding-app
  namespace: flux-system
spec:
  interval: 1m
  retryInterval: 1m
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging/linkding
  prune: true
  targetNamespace: linkding
  decryption:
    provider: sops
    secretRef:
      name: sops-age
