apiVersion: v1
kind: Secret
metadata:
    name: secret-redis
data:
    password: ENC[AES256_GCM,data:Y4fsVfplgKjdceqqS+GVwEBzdwqvdDZHjZ9MApKkNAenJcECPN9gp1QNKFo=,iv:0z1tKTer4Brq8RSwlhCrp0LBBWm9U1LLw58iC2HC/CU=,tag:1001+5OW+B8mSOMCL7suwg==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5REk2amFCRzlBVmdIM1NJ
            WllFQ0c2aXkzWTNjV3ltdUZ0eENjZExXeHgwCnQrMGdCLzd4U2dRVVA0enZrcXM4
            dUFyQjkzTnRnMFNmWmowVjZyVEUramsKLS0tIHV2V2hNbGhIa0IvSEg3THk3NUQz
            ZW83ODVLWnFxVC84dUpQb0IrL0JqYTQKGX7IaXnQHhIVMiHz+O4hDg3Cv67CT7Py
            r8YvekNmYov1a+sXN/jcmU8d6hjeqN7yhsbeAMOSKRloSb+0PeZWQQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-21T00:37:36Z"
    mac: ENC[AES256_GCM,data:12pnsCs2SxGegGEyXh7ViHA1jKCsadZegc+SmfeBob/e8wImfTfxBIqEuImfYPZFq81I9eh2Na9z/i2Hsl0liaPWX9sQ+t+eHH3wqKVeQrU5//YqhJ/MKMMUX7Rv883luoe2cokCTvgVGQPVECn7SmOner3eQgKVLUr/MO2E+0I=,iv:eFkTs+jLlX2aiEyzMSQLASuP2b7kQuU7kZAmW2zVOyg=,tag:NfilTzUPEK5NafQV28DvDA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
