apiVersion: v1
kind: Secret
metadata:
    name: secret-superuser
data:
    password: ENC[AES256_GCM,data:97/NpyrpYu5Sfs/u2eckSgASDFpuuWK8X4S24Y3IxFoZBYw7TYaQ8Ab1Ne1mANyoRe332w==,iv:rUNn/q3Pho3XMfNjtfQpqsyqWb+3399yun0go+FU35w=,tag:M1mZk6BRlna2OO+be4f92w==,type:str]
    username: ENC[AES256_GCM,data:x1YE5c7llUk=,iv:Pp0Ryu++PQIL3Axogr8b2cDtX6uxJyVY0rFwFbVi0vw=,tag:sPXyntRCaFhfQj4IHKaTdQ==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLYzNpbXBpdkVBQmlMelI2
            RUEzVloyRjU0TStKdmtUWllxb2RwM1M4MFJFCjZrS3lKTUFLa1pxUWpiVGhIaVY0
            bDlpMUdMQWZRMEl1eDVXZFRDL3lITHcKLS0tIE4vaFNjendUbk90RGk4U0tTYWR2
            MXQyT0daSGxSVEdHQ29BY2xhbE5rOFkKzXcRQmSSs8ysZifkahMAwjEJaGNLXYx4
            SWo/rWIoJHgUajYb9uj1PtK/SLkApVzg91e0t1XQ0zHwh8hUejV1Ew==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-20T21:31:23Z"
    mac: ENC[AES256_GCM,data:BWN7CwIG8SYQnlp8eoGraIe+JmQ7NPLoLj+HcUXnrySIs9o/QZNnWEfuks09AMIcuhatDXJYB3TZ2QX8HUfOmp8mSKJ0mSRRN396MRX2VizNHSmdN/qiikw8uTY/iYv+iJxs2zGtAtVFj+UAvz/PSujah76GxMaZHV8e2M169FA=,iv:XSugeZDL9Wm91nIscqIe7oUdVX1hBfN1UHuiT6tefmY=,tag:VjI1w7fu+BcGohhOyQk1fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
