apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: "41.x"

      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: traefik
      interval: 12h
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values:
    service:
      annotations:
        metallb.io/loadBalancerIPs: 10.10.10.240
      spec:
        type: LoadBalancer
    ingressClass:
      enabled: true
      isDefaultClass: true
      name: traefik
