apiVersion: v1
kind: Secret
metadata:
    name: secret-superuser
    namespace: linkding
data:
    LD_SUPERUSER_NAME: ENC[AES256_GCM,data:Xm1QrbPjZj0=,iv:8Q+4XNLzb04dB59TQRTfN+uVyn+mi1jUELSm8Zhi550=,tag:b67tuyItoAzgcDXS/QpNew==,type:str]
    LD_SUPERUSER_PASSWORD: ENC[AES256_GCM,data:4I9oW+l8xWt8o+g2aDU7anjNSFBiGMlV,iv:TEQ/UYvwMEdWwh7/C7cC8n//Y5WaIh/ceiUVnGiEqJM=,tag:hHyQWwl+0Xoz+DMa9TqxiQ==,type:str]
sops:
    age:
        - recipient: age1fnjrxtk0cndvgz9sa65f4yv98xygl93nnutltd7s6t6jph0wwywqesleq8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxUU51T254QnNoNEIzbzBM
            aVo4MDBGa3BMUU1BSG92QXYrVlYzNmJ3L3c4CmpkSURPU0gxdENoYk9rNnI2cjhm
            cHZKdjU3NE00c2c5NTV1Wks4SU5nZlkKLS0tIHdMczR1TFRHUlpvSDFMWU5WSzJN
            dTVFcUorUExrdUN4Q2k2TlVCT3V2aWMK19xOetyIfhvMv4j9WHiTPeEwYrjF3ezF
            gXBF5P6bmvNHQfQDmzAxkEwflfPXlyl8EX00049xdxaqXEMCMAfzNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-05T00:49:48Z"
    mac: ENC[AES256_GCM,data:ymGZzxHgbBA4VIheIlhInF1KzSbj5IKkSNlQPrzUxj/0c88tBF0UYXBhKPQWtA2Jo/uuqBLQruNhoNh/mbTgvKDre6SBdGz5rfUP6XqHpxoQi9Voos06I3gbzI04IhuihayDgoWZM20Z7QzKLL9WFcN4EG54R2psbHqhg9+/y2A=,iv:AeWWPc4jIwwvO2yvFt7gVVv81K5Xi3fpZ0uTiUScSXg=,tag:7d/7J2bNCnK4DBNwZC1dPA==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
